FROM python:latest

RUN --name postgres-1 -e POSTGRES_USER=chrisv -e  POSTGRES_PASSWORD=NWO -e POSTGRES_DB=movies -d -p 5432:5432 postgres:alpine

COPY requirements.txt requirements.txt
COPY movieagg.py movieagg.py

RUN pip install -r requirements.txt

CMD ["python", "./movieagg.py"]