version: '3'
services:
  movieagg:
    build:  .
    image: nwocasestudy
    container_name: movieagg
    command: python ./movieagg.py
    depends_on: 
        - db

  db:
    image: postgres:alpine
    environment: 
        - POSTGRES_USER=chrisv 
        - POSTGRES_PASSWORD=NWO 
        - POSTGRES_DB=movies 
    ports:
        - "5432:5432"
    container_name: "postgres_db"

